#!/usr/bin/env python3
"""Build the website's complete notes library from repository Markdown and PDFs."""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "DataStructures_Documentation"
PDF_DIR = ROOT / "Python_Course"
OUTPUT = ROOT / "website" / "assets" / "js" / "content-library-data.js"


def title_from_markdown(text: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def clean_pdf_text(text: str) -> str:
    lines = [line.rstrip() for line in text.replace("\x00", "").splitlines()]
    cleaned: list[str] = []
    blank = False
    for line in lines:
        if not line.strip():
            if not blank:
                cleaned.append("")
            blank = True
            continue
        blank = False
        cleaned.append(line)
    return "\n".join(cleaned).strip()


def category_for(path: Path) -> str:
    name = path.stem.lower()
    if any(word in name for word in ("sort", "search", "complexity", "adaptive", "stable")):
        return "Algorithms"
    if any(word in name for word in ("numpy", "pandas")):
        return "Data Science"
    if "oop" in name:
        return "OOP"
    if "index" in name or "readme" in name:
        return "Index"
    return "Data Structures"


items: list[dict[str, object]] = []

for path in sorted(DOCS_DIR.rglob("*.md")):
    text = path.read_text(encoding="utf-8")
    rel = path.relative_to(ROOT).as_posix()
    items.append(
        {
            "id": "md-" + re.sub(r"[^a-z0-9]+", "-", rel.lower()).strip("-"),
            "title": title_from_markdown(text, path.stem.replace("_", " ")),
            "source": "Markdown",
            "category": category_for(path),
            "path": rel,
            "content": text,
            "lines": len(text.splitlines()),
        }
    )

for path in sorted(PDF_DIR.glob("*.pdf")):
    result = subprocess.run(
        ["pdftotext", "-layout", str(path), "-"],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    pages = [clean_pdf_text(page) for page in result.stdout.split("\f") if page.strip()]
    title = path.stem.replace("_", " ")
    if path.name == "OOPs_Notes.md.pdf":
        title = "Complete OOPs Notes: Beginner to Interview-Ready"
    items.append(
        {
            "id": "pdf-" + re.sub(r"[^a-z0-9]+", "-", path.stem.lower()).strip("-"),
            "title": title,
            "source": "PDF",
            "category": "OOP" if "oop" in path.name.lower() else "Course Lectures",
            "path": path.relative_to(ROOT).as_posix(),
            "content": "\n\n".join(pages),
            "pages": pages,
            "lines": sum(len(page.splitlines()) for page in pages),
        }
    )

payload = json.dumps(items, ensure_ascii=False, separators=(",", ":"))
OUTPUT.write_text(
    "// Generated by tools/build_content_library.py. Do not edit manually.\n"
    f"const CONTENT_LIBRARY = {payload};\n",
    encoding="utf-8",
)
print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(items)} complete documents.")
